import type { WorkspaceState } from '../domain/models';

export function createSeedWorkspace(): WorkspaceState {
  return {
    version: 1,
    project: {
      id: 'project-afterlight',
      title: 'Afterlight: Material Memory',
      venue: 'North Hall / Gallery 3',
      audience: 'General visitors, age 12+',
      openingDate: '2027-03-18',
      stage: 'review',
    },
    artifacts: [
      {
        id: 'artifact-lantern',
        accessionId: 'AF-1908-014',
        title: 'Railway Signal Lantern',
        maker: 'H. B. Cooke & Co.',
        yearLabel: 'c. 1908',
        medium: 'Brass, glass, cotton wick',
        origin: 'York, England',
        summary: 'A hand-carried signal lantern whose worn handle records decades of night work along regional rail lines.',
        dimensions: { width: 19, height: 34, depth: 18, unit: 'cm' },
        dwellMinutes: 4,
        narrativeRole: 'threshold',
        sensitivity: 'standard',
        accessibilityNeed: 'none',
        isKeyObject: true,
        tags: ['labor', 'light', 'rail'],
        color: '#d7654e',
        createdAt: '2026-08-11T09:00:00.000Z',
        updatedAt: '2026-08-11T09:00:00.000Z',
      },
      {
        id: 'artifact-sample-book',
        accessionId: 'AF-1926-203',
        title: 'Dyer’s Sample Book',
        maker: 'Mina Alvarez Workshop',
        yearLabel: '1926–1931',
        medium: 'Textile, ink, paper',
        origin: 'Barcelona, Spain',
        summary: 'A compact archive of hand-dyed threads documenting subtle shifts in color recipes across five working seasons.',
        dimensions: { width: 28, height: 36, depth: 5, unit: 'cm' },
        dwellMinutes: 6,
        narrativeRole: 'context',
        sensitivity: 'low-light',
        accessibilityNeed: 'seating',
        isKeyObject: true,
        tags: ['textile', 'archive', 'color'],
        color: '#7c6aa6',
        createdAt: '2026-08-11T09:05:00.000Z',
        updatedAt: '2026-08-11T09:05:00.000Z',
      },
      {
        id: 'artifact-press',
        accessionId: 'AF-1952-088',
        title: 'Portable Letterpress',
        maker: 'Shinsei Works',
        yearLabel: '1952',
        medium: 'Cast iron, steel, rubber',
        origin: 'Osaka, Japan',
        summary: 'A compact press used by neighborhood organizers to print event notices, mutual-aid cards, and public messages.',
        dimensions: { width: 42, height: 51, depth: 38, unit: 'cm' },
        dwellMinutes: 7,
        narrativeRole: 'turning-point',
        sensitivity: 'standard',
        accessibilityNeed: 'tactile-alternative',
        isKeyObject: true,
        tags: ['print', 'community', 'machine'],
        color: '#2f7c75',
        createdAt: '2026-08-11T09:10:00.000Z',
        updatedAt: '2026-08-11T09:10:00.000Z',
      },
      {
        id: 'artifact-radio',
        accessionId: 'AF-1968-117',
        title: 'Kitchen Table Radio',
        maker: 'Morrow Electronics',
        yearLabel: '1968',
        medium: 'Bakelite, copper, fabric',
        origin: 'Detroit, United States',
        summary: 'A domestic radio repaired repeatedly by one family, carrying music and news through three generations.',
        dimensions: { width: 33, height: 22, depth: 18, unit: 'cm' },
        dwellMinutes: 5,
        narrativeRole: 'context',
        sensitivity: 'standard',
        accessibilityNeed: 'audio',
        isKeyObject: false,
        tags: ['sound', 'repair', 'home'],
        color: '#c7903d',
        createdAt: '2026-08-11T09:15:00.000Z',
        updatedAt: '2026-08-11T09:15:00.000Z',
      },
      {
        id: 'artifact-quilt',
        accessionId: 'AF-1979-031',
        title: 'Rain Map Quilt',
        maker: 'Aisha Green and the East Ward Circle',
        yearLabel: '1979',
        medium: 'Cotton, wool, embroidery thread',
        origin: 'Kingston, Jamaica',
        summary: 'A community quilt mapping remembered storms through stitched paths, dates, and fragments of household cloth.',
        dimensions: { width: 210, height: 176, depth: 2, unit: 'cm' },
        dwellMinutes: 8,
        narrativeRole: 'turning-point',
        sensitivity: 'low-light',
        accessibilityNeed: 'seating',
        isKeyObject: true,
        tags: ['textile', 'climate', 'community'],
        color: '#3f6fa8',
        createdAt: '2026-08-11T09:20:00.000Z',
        updatedAt: '2026-08-11T09:20:00.000Z',
      },
      {
        id: 'artifact-bowl',
        accessionId: 'AF-1987-064',
        title: 'Mended Serving Bowl',
        maker: 'Unknown maker',
        yearLabel: 'c. 1987',
        medium: 'Stoneware, brass staples',
        origin: 'Seoul, South Korea',
        summary: 'A household bowl held together by visible repairs, preserving evidence of care rather than hiding damage.',
        dimensions: { width: 31, height: 12, depth: 31, unit: 'cm' },
        dwellMinutes: 4,
        narrativeRole: 'reflection',
        sensitivity: 'fragile',
        accessibilityNeed: 'none',
        isKeyObject: false,
        tags: ['repair', 'domestic', 'ceramic'],
        color: '#8c9474',
        createdAt: '2026-08-11T09:25:00.000Z',
        updatedAt: '2026-08-11T09:25:00.000Z',
      },
      {
        id: 'artifact-tape',
        accessionId: 'AF-1994-052',
        title: 'Oral History Tape 12',
        maker: 'Riverside Memory Project',
        yearLabel: '1994',
        medium: 'Magnetic tape, plastic, paper',
        origin: 'Glasgow, Scotland',
        summary: 'One cassette from a neighborhood oral-history project, containing recollections of factories after closure.',
        dimensions: { width: 10, height: 6, depth: 1.2, unit: 'cm' },
        dwellMinutes: 6,
        narrativeRole: 'reflection',
        sensitivity: 'standard',
        accessibilityNeed: 'audio',
        isKeyObject: false,
        tags: ['voice', 'memory', 'industry'],
        color: '#a55f72',
        createdAt: '2026-08-11T09:30:00.000Z',
        updatedAt: '2026-08-11T09:30:00.000Z',
      },
      {
        id: 'artifact-gloves',
        accessionId: 'AF-2001-019',
        title: 'Conservator’s Gloves',
        maker: 'Elena Matić',
        yearLabel: '2001–2018',
        medium: 'Cotton, graphite, pigment',
        origin: 'Zagreb, Croatia',
        summary: 'A series of marked gloves retained by a conservator, each pair bearing traces from a completed treatment.',
        dimensions: { width: 24, height: 31, depth: 3, unit: 'cm' },
        dwellMinutes: 3,
        narrativeRole: 'reflection',
        sensitivity: 'standard',
        accessibilityNeed: 'none',
        isKeyObject: false,
        tags: ['care', 'conservation', 'trace'],
        color: '#597b8e',
        createdAt: '2026-08-11T09:35:00.000Z',
        updatedAt: '2026-08-11T09:35:00.000Z',
      },
    ],
    zones: [
      {
        id: 'zone-arrival',
        name: 'Arrival / A Light Carried',
        shortLabel: 'Arrival',
        thesis: 'Material memory begins with an object carried through work and darkness.',
        capacityMinutes: 10,
        maxObjects: 3,
        lowLight: false,
        hasSeating: false,
        color: '#d7654e',
        sequence: 0,
        artifactIds: ['artifact-lantern'],
      },
      {
        id: 'zone-patterns',
        name: 'Patterns of Work',
        shortLabel: 'Patterns',
        thesis: 'Repeated gestures become records: recipes, repairs, impressions, and sound.',
        capacityMinutes: 18,
        maxObjects: 4,
        lowLight: true,
        hasSeating: true,
        color: '#7c6aa6',
        sequence: 1,
        artifactIds: ['artifact-sample-book', 'artifact-radio'],
      },
      {
        id: 'zone-common',
        name: 'The Common Thread',
        shortLabel: 'Common Thread',
        thesis: 'Objects become civic tools when communities make meaning together.',
        capacityMinutes: 20,
        maxObjects: 4,
        lowLight: true,
        hasSeating: true,
        color: '#2f7c75',
        sequence: 2,
        artifactIds: ['artifact-press', 'artifact-quilt'],
      },
      {
        id: 'zone-after',
        name: 'Afterlives',
        shortLabel: 'Afterlives',
        thesis: 'Repair and retelling keep an object active after its first use has ended.',
        capacityMinutes: 15,
        maxObjects: 4,
        lowLight: false,
        hasSeating: true,
        color: '#597b8e',
        sequence: 3,
        artifactIds: ['artifact-bowl', 'artifact-tape'],
      },
    ],
    issues: [
      {
        id: 'issue-audio-transcript',
        title: 'Add transcript beside oral history station',
        description: 'The current audio treatment needs a synchronized transcript and a printed fallback.',
        severity: 'critical',
        status: 'in-progress',
        zoneId: 'zone-after',
        artifactId: 'artifact-tape',
        owner: 'Mara Chen',
        createdAt: '2026-08-20T10:00:00.000Z',
        updatedAt: '2026-09-01T14:30:00.000Z',
      },
      {
        id: 'issue-entry-copy',
        title: 'Reduce entry panel copy',
        description: 'The opening panel currently competes with the lantern sightline and should be shortened.',
        severity: 'warning',
        status: 'open',
        zoneId: 'zone-arrival',
        owner: 'Theo James',
        createdAt: '2026-08-23T12:00:00.000Z',
        updatedAt: '2026-08-23T12:00:00.000Z',
      },
      {
        id: 'issue-quilt-light',
        title: 'Confirm quilt lux rotation',
        description: 'Conservation confirmed the zone level; document the planned three-month rotation.',
        severity: 'note',
        status: 'resolved',
        zoneId: 'zone-common',
        artifactId: 'artifact-quilt',
        owner: 'Rina Solberg',
        createdAt: '2026-08-18T09:00:00.000Z',
        updatedAt: '2026-08-28T16:00:00.000Z',
        resolvedAt: '2026-08-28T16:00:00.000Z',
      },
    ],
    preferences: {
      pace: 'balanced',
      accessibilityPriority: 70,
      groupSize: 6,
    },
    scenarioRecords: [],
    lastSavedAt: '2026-09-01T14:30:00.000Z',
  };
}
